components:
  schemas:
    UserRegister:
      properties:
        email:
          format: email
          type: string
        name:
          type: string
      required:
        - email
        - name
      type: object
    UserStatus:
      type: string
      enum:
        - active
        - suspended
        - deactivated
    User:
      properties:
        createdAt:
          format: date-time
          type: string
        email:
          type: string
        id:
          type: string
        name:
          type: string
        status:
          $ref: '#/components/schemas/UserStatus'
        updatedAt:
          format: date-time
          type: string
      required:
        - createdAt
        - email
        - id
        - name
        - status
      type: object
    Error:
      properties:
        code:
          type: string
        errors:
          items:
            type: string
          type: array
        message:
          type: string
      required:
        - message
      type: object
info:
  description: API
  title: API
  version: 1.0.0
openapi: 3.0.0
paths:
  /user/register:
    post:
      operationId: userRegister
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                required:
                  - user
                type: object
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unprocessable Entity
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server
      tags:
        - user
      x-eov-operation-handler: user
servers:
  - description: Production
    url: https://api.company.com
